config/routes.rb
FayeAnime::Application.routes.draw do
  devise_scope :user do
    match "/users" => "Registrations#create"
  end

  resources :categories, :except => [:index, :show]
  resources :forums, :except => :index do
    resources :topics, :shallow => true, :except => :index do
      resources :posts, :shallow => true, :except => [:index, :show]
    end
    root :to => 'categories#index', :via => :get
  end

  resources :animes, :only => [:index, :show]

  resources :episodes, :only => :show
  match 'episodes/comments' => 'episodes#comments', via: :post, as: :comments
  match 'search' => 'animes#search', via: :get, as: :anime_search
  post 'episodes/report'


  root to: "home#index"
  match ':name' => 'Users#show', as: :user

  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks"}
  resources :users, only: :show

  resources :animes do
    get :autocomplete_episode_title, :on => :collection
  end

end

app/models/episode.rb
class Episode < ActiveRecord::Base
  validates :title, :uniqueness => { :case_sensitive => false }, :presence => true
  has_many :comments
  has_many :episodes_report
  belongs_to :anime
  scope :previous, lambda { |p| {:conditions => ["episode_number < ? && anime_id = ?", p.episode_number, p.anime_id], :limit => 1, :order => "episode_number DESC"} }
  scope :next, lambda { |p| {:conditions => ["episode_number > ? && anime_id = ?", p.episode_number, p.anime_id], :limit => 1, :order => "episode_number"} }
  before_save :default_values

  define_index do
    indexes :title
    indexes :episode_number
  end

  def to_param
    "#{id}-#{title.parameterize}"
  end

  def default_values
    self.counter ||= 0
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_filter :authenticate_user!, :only => [:comments]

  def report
    respond_to do |format|
      format.js do
        episode = Episode.find(params[:episode_id])
        url = "http://www.gogoanime.com/#{episode.title.parameterize}".gsub(/-episode/, '')

        attempts = 0
        begin
          Scraper::GoGoAnime.new(url, :episode => episode).update_episode
        rescue Exception => e
          puts url = "http://www.gogoanime.com/#{episode.title.parameterize}-#{episode.title.parameterize}".gsub(/-episode/, '')
          attempts += 1
          retry unless attempts > 1
          Rails.logger.info e
        ensure
          episode.update_attribute(:fixed_at, Time.now)
        end

        render :json => {}
      end
    end
  end

  def show
    @episode = Episode.find(params[:id])
    @episode.update_attribute(:counter, @episode.counter + 1)

    @comment = Comment.new

    @previous_episode = Episode.previous(@episode).first
    @next_episode = Episode.next(@episode).first

    @comments = Kaminari.paginate_array(@episode.comments.reverse).page(params[:page]).per(10)
  end

  def comments
    respond_to do |format|
      format.js do
        @comment = Comment.create(:user_id => current_user.id, :episode_id => params[:comment][:episode_id], :comment_body => params[:comment][:comment_body])
      end
    end
  end

end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/_episode_navigation.html.erb
<span data-episode-id="<%= @episode.id %>" class="btn btn-warning btn-report-episode">
  <span class="icon-report icon-warning-sign"></span>
  Fix Broken Video
</span>


<ul class="nav nav-tabs tabs" data-tabs="tabs" ></ul>

<div class="pagination-container">
  <% unless @previous_episode.nil? %>
    <div class="previous-episode">
      <%= link_to 'Previous Episode', episode_path(@previous_episode) %>
    </div>
  <% end %>

  <% unless @next_episode.nil? %>
    <div class="next-episode"> 
      <%= link_to 'Next Episode', episode_path(@next_episode) %>
    </div>
  <% end %>
</div>

app/views/episodes/_report_dialog.html.erb
<div id="report-episode-modal" class="modal hide fade" style="display: none; ">
  <span class="report-episode-id" style="display:none;"><%= @episode.id %></span>
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>Reporting <%= @episode.title.titleize %></h3>
  </div>
  <div class="modal-body">
    <div class="alert alert-error" style="display:none;">
      Please fill in a description.
    </div>
    <p>
      Thank you for reporting this episode. We will be sure to have it fixed as soon as possible.
    </p>
    <form class="well">
      <label>Description:</label>
      <input type="text" class="episode-modal-text span3" placeholder="What went wrong?">
      <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal">Close</a>
        <span class="btn btn-primary">Submit</button>
      </div>
    </form>
  </div>
</div>

app/views/episodes/comments.js.erb
$('.table').prepend("<tr><td><%= j @comment.user.facebook_avatar %></td><td><span><%= j @comment.comment_body %></span><div><%= j(link_to @comment.user.name, user_path(@comment.user.id)) %><%= @comment.created_at %></div></td></tr>");

app/views/episodes/edit.html.erb
<h1>Episodes#edit</h1>
<p>Find me in app/views/episodes/edit.html.erb</p>

app/views/episodes/show.html.erb
<%= title(@episode.title) %>

<% if @episode.episode_number.nil? %>
  <h2 class="episode-title"><%= link_to @episode.title.titleize, anime_path(@episode) %></h2>
<% else %>
  <h2 class="episode-title"><%= link_to "#{@episode.anime.title.titleize} Ep. #{@episode.episode_number}", anime_path(@episode.anime_id) %></h2>
<% end %>

<%= render :partial => 'episode_navigation' %>

<span class='span6 video-background'>
  <div class="tab-content">
    <%=  @episode.embed_url.html_safe %>
  </div>
</span>

<span class="comment-section">
  <fb:like send="true" href="<%= request.url %>" width="450" show_faces="true"></fb:like>
  <fb:comments href="<%= episode_url(@episode) %>" num_posts="2" width="900"></fb:comments>
</span>