config/routes.rb
FayeAnime::Application.routes.draw do
  devise_scope :user do
    match "/users" => "Registrations#create"
  end

  resources :categories, :except => [:index, :show]
  resources :forums, :except => :index do
    resources :topics, :shallow => true, :except => :index do
      resources :posts, :shallow => true, :except => [:index, :show]
    end
    root :to => 'categories#index', :via => :get
  end

  resources :animes, :only => [:index, :show]

  resources :episodes, :only => :show
  match 'episodes/comments' => 'episodes#comments', via: :post, as: :comments
  match 'search' => 'animes#search', via: :get, as: :anime_search
  post 'episodes/report'


  root to: "home#index"
  match ':name' => 'Users#show', as: :user

  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks"}
  resources :users, only: :show

  resources :animes do
    get :autocomplete_episode_title, :on => :collection
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  
  # Associations
  has_many :forums, :dependent => :destroy
  
  # Accessors
  attr_accessible :title, :state, :position, :category_id
  
  # Scopes
  default_scope :order => 'position ASC'
  
  # Validations
  validates :title,       :presence => true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    @category = Category.new
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category])

    if @category.save
      flash[:notice] = "Category was successfully created."
      redirect_to forums_url
    else
      render :action => 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update_attributes(params[:category])
      flash[:notice] = "Category was updated successfully."
      redirect_to forums_url
    end
  end

  def destroy
    @category = Category.find(params[:id])

    if @category.destroy
      flash[:notice] = "Category was deleted."
    end

    redirect_to forums_url
  end
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>New Category</h3>
  </div>
  <div class="modal-body">
    <% if @category.errors.any? %>
      <% flash.now[:error] = @category.errors.full_messages.join(', and ') %>
    <% end %>
    <%= f.text_field :title, :size => 75, :placeholder => 'Title' %>


    <%= f.label :position %>
    <%= f.text_field :position %>

    <%= f.label :state %>
    <%= f.check_box :state %><br>
  </div>
  <div class="modal-footer">
    <%= f.submit "Create Forum Category", :class => "btn-warning btn" %>
    <a class="btn" data-dismiss="modal">Close</a>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= form_for @category do |f| %>
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>Edit Category</h3>
  </div>
  <div class="modal-body">
    <% if @category.errors.any? %>
      <% flash.now[:error] = @category.errors.full_messages.join(', and ') %>
    <% end %>
    <%= f.text_field :title, :size => 75, :placeholder => 'Title' %>


    <%= f.label :position %>
    <%= f.text_field :position %>

    <%= f.label :state %>
    <%= f.check_box :state %><br>
  </div>
  <div class="modal-footer">
    <%= f.submit "Create Forum Category", :class => "btn-warning btn" %>
    <a class="btn" data-dismiss="modal">Close</a>
  </div>
<% end %>

app/views/categories/index.html.erb
<% if is_moderator? %>
  <div class="right controls"><%= link_to "New Forum Category", '#new-forum-category', :'data-toggle' => "modal" %></div>
  <div style='display:none;' class='modal fade' id='new-forum-category'>
    <%= render :partial => 'form' %>
  </div>
<% end %>

<% if is_moderator? %>
  <div style='display:none;' class='modal' id='edit-forum-category'>
    <%= render :partial => 'form' %>
  </div>
<% end %>

<% @categories.each do |category| %>
  <div class="module">
    <div class="module_header">
      <%= category.title.titleize %>
      <% if is_moderator? %>
        <span class="controls right smaller">
          <%= link_to "New Forum", new_forum_path %>
          <%= link_to "Edit Category", edit_category_path(category) %>
          <%= link_to "Delete Category", category_path(category), :confirm => "Are you sure you want to delete this category?", :method => :delete %>
        </span>
      <% end %>
    </div>
    <% if category.forums.size > 0 %>
    <div>
      <table class="table table-bordered table-striped">
        <tr class="smaller">
          <th align="left">Forum</th>
          <th>Topics</th>
          <th>Posts</th>
          <th class="last_post" align="left">Last Post</th>
        </tr>
        <% category.forums.each do |forum| %>
        <tr>
          <td class="description">
            <%= link_to forum.title, forum_path(forum) %><br />
            <span class="smaller"><%= forum.description %></span><br />
          </td>
          <td class="counts smaller"><%= forum.topics.size %></td>
          <td class="counts smaller"><%= forum.posts.size - forum.topics.size %></td>
          <td class="last_post smaller">
            <span class="icon"><%= image_tag 'default_avatar.png',  :style => "width:30px" %>&nbsp;</span>
            <% if forum.posts.size > 0 %>
              <%= forum.posts.last.created_at %><br />
              <%= forum.posts.last.user.name %>
            <% else %>
              No Topics / Posts
            <% end %>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
    <% else %>
      <div class="module_body">There are currently no forums.</div>
    <% end %>
  </div>
<% end %>

app/views/categories/new.html.erb
<%= render :partial => 'form' %>